In [ ]:
# BASED ON scikit learn DOCUMENTATION

import numpy as np
import pandas as pd
import sklearn


from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import fetch_openml
from sklearn.utils import check_random_state
from sklearn.model_selection import train_test_split

# The Data

The MNIST dataset consists of 70,000 handwritten digits used to evaluate algorithms for classification - more details can be found [here](http://yann.lecun.com/exdb/mnist/).

In [ ]:
# OBTAIN

# DATA AVAILABLE @ https://www.openml.org/d/554
# THERE ARE MANY SOURCES OF THE MNIST DATA - THIS IS ONE

X, y = fetch_openml('mnist_784', version=1, return_X_y=True)


# Scrub


In [ ]:
# SCRUB
random_state = check_random_state(0)
permutation = random_state.permutation(X.shape[0])
X = X[permutation]
y = y[permutation]
X = X.reshape((X.shape[0], -1))

In [ ]:
# SCRUB - FOR TESTING USE SMALLER
# k-nearest neighbor algo runtime >= 150 mins | train_samples = 60000

train_samples=6000
#train_samples = 60000

In [ ]:
# SCRUB - TEST / TRAIN SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=train_samples, test_size=10000)

# Bayes

Naive Bayes are a set of supervised learning algorithms - more details [here](https://scikit-learn.org/stable/modules/naive_bayes.html#naive-bayes)

In [ ]:
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score

In [ ]:
# MODEL

# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(X_train, y_train)

In [ ]:
# MODEL

# Make predictions
preds = gnb.predict(X_test)
# print(preds)

In [ ]:
# MODEL

# Evaluate accuracy
print(accuracy_score(y_test, preds))

0.564


In [ ]:
# INTERPRET

expected = y_test
predicted = preds
print(sklearn.metrics.confusion_matrix(expected, predicted))

[[ 910    1    6    2    4    2   25    0   29   18]
 [   1 1055    3    3    1    4   12    0   25   18]
 [  86   32  336   39    7    4  266    2  210   20]
 [  78   56    8  337    1    1   63   12  336  110]
 [  23    1    6    2  144    5  100    7  190  492]
 [ 108   22    3   21    4   43   47    2  535   92]
 [  12   14    7    1    0    3  923    0   20    1]
 [   4    6    1    8    8    1    3  330   27  659]
 [  13  126    7    8    4    5   12    1  605  201]
 [   5   11    4    2   12    1    1   14   13  957]]


# K-Nearest Neighbors


NOTE: K-Nearest Neighbors is a "lazy" algorithm - the separation of test & training is not truly necessary - more details available at https://scikit-learn.org/stable/modules/neighbors.html

In [ ]:
# MODEL BUILD - K-Nearest Neighbors - Just fit/score entire sample

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
neigh.score(X, y)


0.9870714285714286

# Random Forest

A random forest is an ensemble of decision trees.  More details can be found [here](https://web.archive.org/web/20160417030218/http://ect.bell-labs.com/who/tkh/publications/papers/odt.pdf)


In [ ]:
# MODEL BUILD - RANDOM FORESTS

from sklearn.ensemble import RandomForestClassifier 

forest = RandomForestClassifier(n_estimators = 100)
forest.fit(X_train, y_train)
print('Score: ', forest.score(X_test, y_test))
predictions = forest.predict(X_test)

Score:  0.9411


In [ ]:
expected = y_test
predicted = predictions
print(sklearn.metrics.confusion_matrix(expected, predicted))